name: Audit & Test

on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]

jobs:
  security-audit:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        # fail on moderate or higher (exit code ≠0 if any found)
        run: npm audit --audit-level=moderate

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: security-audit
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm ci
      - run: npm test
